### ISSUE TITLE
Error : d.bootstrapSwitch is not a function

### ISSUE THREAD

**Issue by naokha** [frapontillo/angular-bootstrap-switch#87]
I'm trying to use your nice library, but I get this error in the web console : 
'd.bootstrapSwitch is not a function'
AngularJS 1.3.16, bootstrap 3.3.5, bootstrap-switch, bootstrap-angular-switch, jquery 1.11.3 are included in my project and loaded (I took care of checking it in the web console).
Any idea ?

Thanks.

**Comment by frapontillo** [comment]
Please [read this first](https://github.com/frapontillo/angular-bootstrap-switch/blob/develop/CONTRIBUTING.md#-report-an-issue).

**Comment by naokha** [comment]
I could not reproduce a live demo. 
It's finally working with tag version 0.4.0.
Issue is closed.

**Comment by frankvictor** [comment]
Seems the same reason with #64 , could try it.

**Comment by Andsbf** [comment]
I'm facing the same problem, I'm using the minified file in my angular project, that is the front end of my rails app.

**Comment by arseneoaa** [comment]
Hello,

I had the same issue when I did not add all js files: angular-bootstrap-swith.js (directive) + bootstrap-switch.js (in its dependencies). Loading this last one solved it for me.

Just check the example and make sure to add all needed files.

**Comment by flipjs** [comment]
Im getting the same error when code is minified. Im using ng-poly generator and it uses gulp-uglify. Any work-around on this? Thanks.

**Comment by odedfos** [comment]
In my case I was getting the error because I embedded the module manually (not using bower) but did not embed the bootstrap-switch module as well.
See issue #90

**Comment by nvdh** [comment]
For me this was the same as https://github.com/frapontillo/angular-bootstrap-switch/issues/64, loading jquery before angular solved this.

**Comment by punyfeir** [comment]
plz refer to the plnkr demo you have to include all the css and js files

**Comment by punyfeir** [comment]
http://plnkr.co/edit/SWy8YmrVi8IsTa4FuqSZ?p=info
